# Generated by Django 3.0.5 on 2020-04-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('attached_image', models.ImageField(upload_to='thread_images/%Y/%m/%d/')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.CharField(max_length=200)),
                ('attached_image', models.ImageField(upload_to='thread_images/%Y/%m/%d/')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('linked_counter_arguments', models.ManyToManyField(blank=True, related_name='_replymodel_linked_counter_arguments_+', to='threads.ReplyModel')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.ThreadModel')),
            ],
        ),
    ]
