# Generated by Django 3.0.5 on 2020-04-29 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replymodel',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replys'},
        ),
        migrations.AlterModelOptions(
            name='threadmodel',
            options={'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
        migrations.RenameField(
            model_name='threadmodel',
            old_name='date_posted',
            new_name='time_posted',
        ),
        migrations.AddField(
            model_name='replymodel',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
