# Generated by Django 3.0.5 on 2020-05-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20200430_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymodel',
            name='linked_counter_arguments',
        ),
        migrations.AddField(
            model_name='replymodel',
            name='counter_argument_to',
            field=models.ManyToManyField(blank=True, related_name='_replymodel_counter_argument_to_+', to='threads.ReplyModel'),
        ),
        migrations.AddField(
            model_name='replymodel',
            name='saved_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
